name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose your Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Flask app
        run: |
          # You can add any additional setup commands here
          # For example, if you need to run migrations or other setup tasks
          python weather.py  # Replace with your Flask app file

      - name: Generate static content
        run: |
          # You can add any commands to generate static content if needed

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./main  # Change this to the directory with your static files
